version: "3.8"

services:
  node-app:
    build: .
    environment:
      - PUBLIC_URL=http://localhost:5173
      - PORT=3000
      - DB_USER=hfxokagp
      - DB_PASSWORD=GIxb3Z1fWyL__ACzvHDBwt98xhYEdYyB
      - DB_HOST=peanut.db.elephantsql.com
      - DB_NAME=hfxokagp

      - GOOGLE_CLIENT_ID=164427320400-0miasgfb2q1t67t6n13riscaie7krmd5.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://localhost:3000/openscience/api/v1/auth/google/callback
      - GOOGLE_WINDOW=http://localhost:5173

      - JWT_SECRET=key
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - server-app
    volumes:
      - ./:/server
      - /server/node_modules
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=hfxokagp
      - POSTGRES_USER=hfxokagp
      - POSTGRES_PASSWORD=GIxb3Z1fWyL__ACzvHDBwt98xhYEdYyB
    ports:
      - 5432:5432
    networks:
      - server-app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=marketplace@mail.com
      - PGADMIN_DEFAULT_PASSWORD=marketplace
    ports:
      - 5050:80
    networks:
      - server-app

networks:
  server-app:
    driver: bridge

volumes:
  postgres_data:
    driver: local
